### ISSUE TITLE
Sugestão: adicionar espaço entre a thumbnail e o texto, além de justificar texto

### ISSUE THREAD

**Issue by igorcmelo** [ancapsu/libvw#15]
Em relação a página `/article/:artigo`
### Original
![image](https://user-images.githubusercontent.com/59902451/86434243-59dd0600-bcd3-11ea-8c11-d1cfeae680b4.png)

### Imagem com `margin-left: 20px` e parágrafos com `text-align: justify`
![image](https://user-images.githubusercontent.com/59902451/86434348-a58faf80-bcd3-11ea-9431-e768e67326de.png)

(Adicionei direto do Inspector do Chrome, pois não tenho conhecimento em React, Redux, etc)

**Comment by eduardosoareszup** [comment]
Justificar o texto acredito que não ia ser o ideal. Normalmente se recomenda a usar o texto a esquerda para a maioria dos blogs. Tem alguns artigos bem interessantes falando a respeito como [esse](https://comunidade.rockcontent.com/alinhamento-justificado-versus-a-esquerda/#:~:text=O%20alinhamento%20justificado%20%C3%A9%20aquele,desuniforme%20ao%20longo%20do%20texto.)
