### ISSUE TITLE
Menu no header não abre em celulares pequenos

### ISSUE THREAD

**Issue by peterturguniev** [ancapsu/libvw#3]
O menu em LibVisWeb/LibVisWeb/ClientApp/components/header/HeaderMenu.tsx já está adaptado para mobile, mas algum outro elemento impede que seja clicado quando a largura é pequena demais.

**Comment by Yrds** [comment]
A div dos botões `Login`e `Cadastre-se` estão passando por cima do botão de menu, algumas possíveis soluções seriam apenas diminuir a max-width do elemento:

```
.header-user-box {
  max-width: 360;
}
```

Outra solução sem mudar o tamanho de nada seria tirar o `pointer-events` da div e passar pros elementos dentro dela, assim o tamanho da div não importa já que ela não recebe cliques.

```
.header-user-box {
  pointer-events: none;
}

.header-user-box * {
  pointer-events: all;
}
```

Eu não manjo muito do layout e não entendi direito o porque disso estar acontecendo, por isso sugeri essas soluções pequenas pra não impactar no layout em si.

**Comment by pedromtcosta** [comment]
#11 

Criei uma PR para isso. Vejam se concordam com a solução e se for o caso, façam o merge :)

**Comment by Yrds** [comment]
@pedromtcosta testei aqui, ficou muito bom, bem melhor que minha solução

**Comment by vital-edu** [comment]
Essa issue deveria ser fechada devido ao merge do PR #11 , correto?
