### ISSUE TITLE
Existe a possibilidade de uma refatoração do site?

### ISSUE THREAD

**Issue by darlanhms** [ancapsu/libvw#31]
Aparentemente esse repositório não recebe mais manutenção e o site usa bibliotecas antigas/deprecadas, a UI também tem um ar de ser antiga, existe algum planejamento futuro para refatoração? Se sim, ele seria open source também?

**Comment by thayronepaula** [comment]
@darlanhms Anunciado dia 28/09/2023 pelo Peter em twitter(X): https://twitter.com/ancapsu/status/1707391582385611104.
